### ISSUE TITLE
bukkit ?

### ISSUE THREAD

**Issue by CyberSpongie** [axle2005/DimReseter#1]
Hello can you make a backport to 1.7.10 for bukkit i need something like this so i can able to reset the end without me having to go in the files and delete them 
thanks

**Comment by axle2005** [comment]
I haven't looked at any of Bukkit's API in a long time... but I can take a quick stab at it sometime this week. Its not an overly complicated plugin.

**Comment by CyberSpongie** [comment]
Thanks

**Comment by CyberSpongie** [comment]
hey man any news about this ?

**Comment by axle2005** [comment]
https://github.com/axle2005/EndReset/releases/tag/v1.0

**Comment by axle2005** [comment]
Created separate repository for this.
