### ISSUE TITLE
Duplicate Configs

### ISSUE THREAD

**Issue by Mohron** [axle2005/DimReseter#2]
DimReseter-1.0.2

Dim reseter creates duplicate configs on Ubuntu (probably any case sensitive file system/os)

![image](https://user-images.githubusercontent.com/3623122/28495948-00587dee-6f24-11e7-8a9e-5576ed4d626e.png)

**Comment by alexandre-dupierris** [comment]
Hello !
What is the file we have to use ? DimReseter or dimreseter ?

**Comment by kreezxil** [comment]
so I downloaded today, I guess you had not pushed the fix because I have duplicate configs too. Yep I'm using 1.12-1.0.2

**Comment by axle2005** [comment]
Nope, it wouldn't be in 1.0.2. It will be in 1.0.3.
